# Generated by Django 2.2.6 on 2020-04-18 10:53

import creator.models
from django.db import migrations, models


def forwards_func(apps, schema_editor):
    Songs = apps.get_model("creator", "Song")
    db_alias = schema_editor.connection.alias
    Songs.objects.using(db_alias).all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_song_data'),
    ]

    operations = [
        migrations.RunPython(forwards_func),
        migrations.AlterField(
            model_name='song',
            name='data',
            field=models.FileField(upload_to=creator.models.song_path, validators=[
                creator.models.validate_file_extension
            ]),
        ),
    ]
