# Generated by Django 2.2.6 on 2020-06-05 17:56

import creator.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0006_auto_20200604_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover_image',
            field=models.ImageField(blank=True, storage='django.core.files.storage.FileSystemStorage', upload_to=creator.models.cover_path, validators=[creator.models.validate_image_extension]),
        ),
    ]
