# Generated by Django 2.2.6 on 2020-06-13 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0011_auto_20200613_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 19, 39, 17, 145582)),
        ),
        migrations.AddField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 13, 19, 39, 17, 146581)),
        ),
    ]
