# Generated by Django 2.2.6 on 2020-04-18 10:31

import account_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=account_management.models.profile_picture_path),
        ),
    ]
