# Generated by Django 2.2.6 on 2020-06-05 19:06

import account_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0003_auto_20200605_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(null=True, storage='cloudinary_storage.storage.MediaCloudinaryStorage', upload_to=account_management.models.profile_picture_path),
        ),
    ]
