# Generated by Django 2.2.6 on 2020-06-13 16:46

import account_management.models
import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0006_auto_20200605_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(default=None, null=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to=account_management.models.profile_picture_path),
        ),
    ]
