# Generated by Django 2.2.6 on 2020-06-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_management', '0007_auto_20200613_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
