# Generated by Django 2.2.6 on 2020-06-04 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200604_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commentalbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsAlbum', to='creator.Album'),
        ),
        migrations.AlterField(
            model_name='commentsong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsSong', to='creator.Song'),
        ),
        migrations.AlterField(
            model_name='favoritealbum',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_favorites', to='creator.Album'),
        ),
        migrations.AlterField(
            model_name='favoritealbum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoriteartist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoriteartist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_artists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='favoritesong',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_favorites', to='creator.Song'),
        ),
        migrations.AlterField(
            model_name='favoritesong',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fav_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='songsinplaylist',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs_in_playlist', to='user.Playlist'),
        ),
        migrations.AlterField(
            model_name='songsinplaylist',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_in_playlists', to='user.Playlist'),
        ),
        migrations.AlterField(
            model_name='stream',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to=settings.AUTH_USER_MODEL),
        ),
    ]
