# Generated by Django 2.2.6 on 2020-06-16 22:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0006_auto_20200615_0710'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 6, 17, 0, 17, 59, 435448)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playlist',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='playlist',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PlaylistVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='user.Playlist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
