# Generated by Django 2.2.6 on 2020-06-17 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20200617_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stream',
            name='data',
        ),
    ]
